kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: drools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drools
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: drools
        image: registry.eu-gb.bluemix.net/ipo-drools/hellokie:1.0
        env:
          - name: VERSION
            value: "1"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: drools
spec:
  selector:
    app: drools
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: drools-ingress
spec:
  rules:
  - host: drools.ipotm10cluster.eu-gb.containers.appdomain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: drools
          servicePort: 80
